include:
  - board: seeeduino_xiao_ble
    shield: "cliche_air_r rgbled_adapter"
  - board: seeeduino_xiao_ble
    shield: "cliche_air_l rgbled_adapter"
  - board: seeeduino_xiao_ble
    shield: settings_reset
