file_format: "1"
id: cliche_air
name: Cliche_Air
type: shield
url: https://github.com/nikkyhiro67/zmk-config-Cliche_Air
requires: [seeeduino_xiao_ble]
features:
  - keys
  - rgb
  - battery

variants:
  - id: cliche_air_l
    name: Cliche_Air_Left
    features:
      - central
      - keys
      - encoder
      - rgb
      - battery

  - id: cliche_air_r
    name: Cliche_Air_Right
    features:
      - peripheral
      - keys
      - rgb
      - battery
