manifest:
  version: 1.2

  defaults:
    remote: zmkfirmware
    revision: main

  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: nikkyhiro67
      url-base: https://github.com/nikkyhiro67
    - name: sekigon-gonnoc
      url-base: https://github.com/sekigon-gonnoc
    - name: cormoran
      url-base: https://github.com/cormoran
    - name: caksoylar
      url-base: https://github.com/caksoylar

  projects:
    - name: zmk
      import:
        file: app/west.yml
        path-prefix: external
      clone-depth: 1
    - name: zmk-pmw3610-driver
      remote: nikkyhiro67
      revision: main
      path: external/zmk-pmw3610-driver
      clone-depth: 1
    - name: zmk-feature-non-lipo-battery-management
      remote: sekigon-gonnoc
      revision: main
      path: modules/feature-non-lipo-battery-management
    - name: zmk-driver-animation
      remote: cormoran
      revision: main
      path: external/zmk-driver-animation
      clone-depth: 1
    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: main
      path: modules/rgbled-widget

  self:
    path: config
