manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: nikkyhiro67
      url-base: https://github.com/nikkyhiro67
    - name: caksoylar # <-- new entry
      url-base: https://github.com/caksoylar
    - name: badjeff
      url-base: https://github.com/badjeff

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: badjeff
      revision: main
      path: modules/pmw3610-driver
    - name: zmk-rgbled-widget # <-- new entry
      remote: caksoylar
      revision: main
  self:
    path: config
