manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: nikkyhiro67
      url-base: https://github.com/nikkyhiro67
    - name: caksoylar
      url-base: https://github.com/caksoylar
    - name: sekigon-gonnoc
      url-base: https://github.com/sekigon-gonnoc

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.2.1
      import: app/west.yml

    - name: zmk-pmw3610-driver
      remote: nikkyhiro67
      revision: main
      path: modules/pmw3610-driver

    - name: zmk-driver-animation
      remote: nikkyhiro67
      revision: main

    - name: zmk-driver-ext-power-transient
      remote: nikkyhiro67
      revision: main

    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: main

    - name: zmk-feature-non-lipo-battery-management
      remote: sekigon-gonnoc
      revision: main

  self:
    path: config
