manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: nikkyhiro67
      url-base: https://github.com/nikkyhiro67
    - name: sekigon-gonnoc
      url-base: https://github.com/sekigon-gonnoc
    - name: caksoylar
      url-base: https://github.com/caksoylar

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.2.1
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: nikkyhiro67
      revision: main
      path: modules/pmw3610-driver
    - name: zmk-module-battery-monitor
      remote: nikkyhiro67
      revision: main
      path: modules/zmk-module-battery-monitor
    - name: zmk-module-led-indicator
      remote: nikkyhiro67
      revision: main
      path: modules/zmk-module-led-indicator
    - name: zmk-feature-non-lipo-battery-management
      remote: nikkyhiro67
      revision: main
    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: main
  self:
    path: config
