name: Build Cliche_Air

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shield: [Cliche_Air_L, Cliche_Air_R]
        board: [seeeduino_xiao_ble]

    steps:
      - name: Checkout config (repo)
        uses: actions/checkout@v4
        with:
          path: config

      - name: Checkout ZMK
        uses: actions/checkout@v4
        with:
          repository: zmkfirmware/zmk
          path: zmk
          ref: main

      - name: Install West
        run: python3 -m pip install --upgrade west

      - name: Init west
        working-directory: zmk
        run: west init -l app

      - name: Update west
        working-directory: zmk
        run: west update

      - name: Build (${{ matrix.shield }} - ${{ matrix.board }})
        working-directory: zmk
        run: |
          west build -s app -d build/${{ matrix.shield }} \
            -b ${{ matrix.board }} \
            -- -DZMK_CONFIG=../config \
               -DSHIELD=${{ matrix.shield }} \
               -DZMK_EXTRA_MODULES="$(pwd)/../config"
