name: Build ZMK Firmware
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3.0
    env:
      EXTRA_CMAKE_ARGS: -DZMK_EXTRA_MODULES=${{ github.workspace }}
