name: Build ZMK (Custom Stable)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build gperf ccache dfu-util device-tree-compiler wget xz-utils file

      - name: Install west
        run: pip install west

      - name: Initialize west workspace
        run: |
          west init -l config
          west update --narrow --fetch-opt=--depth=1
          west zephyr-export

      - name: Install Zephyr SDK
        run: |
          wget https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.9/zephyr-sdk-0.16.9_linux-x86_64.tar.xz
          tar xf zephyr-sdk-0.16.9_linux-x86_64.tar.xz
          sudo mv zephyr-sdk-0.16.9 /opt/zephyr-sdk
          /opt/zephyr-sdk/setup.sh -t arm-zephyr-eabi

      - name: Build ZMK firmware (Cliche Air Right)
        env:
          ZEPHYR_TOOLCHAIN_VARIANT: zephyr
          ZEPHYR_SDK_INSTALL_DIR: /opt/zephyr-sdk
        run: |
          west build -s zmk/app -b seeeduino_xiao_ble \
            -- -DZMK_CONFIG=config \
            -DSHIELD="cliche_air_r rgbled_adapter" \
            -DZMK_EXTRA_MODULES=$(pwd)

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: build/zephyr/*.uf2

      - name: Build ZMK firmware (Cliche Air Left)
        env:
          ZEPHYR_TOOLCHAIN_VARIANT: zephyr
          ZEPHYR_SDK_INSTALL_DIR: /opt/zephyr-sdk
        run: |
          west build -s zmk/app -b seeeduino_xiao_ble -d build_left \
            -- -DZMK_CONFIG=config \
            -DSHIELD="cliche_air_l rgbled_adapter" \
            -DZMK_EXTRA_MODULES=$(pwd)

      - name: Upload Left firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware_left
          path: build_left/zephyr/*.uf2
