name: Build ZMK (Custom Stable)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install west + dependencies
        run: |
          pip install west
          sudo apt-get install -y ninja-build gperf

      - name: Initialize west workspace
        run: |
          west init -l config
          west update --narrow --fetch-opt=--depth=1
          west zephyr-export

      - name: Build ZMK firmware (Cliche Air)
        run: |
          west build -s zmk/app -b seeeduino_xiao_ble \
            -- -DZMK_CONFIG=config \
            -DSHIELD="cliche_air_r rgbled_adapter" \
            -DZMK_EXTRA_MODULES=$(pwd)

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: build/zephyr/*.uf2
