name: Build Cliche_Air

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shield: [cliche_air_l, cliche_air_r]
        board: [seeeduino_xiao_ble]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install West
        run: pip3 install west

      - name: Initialize west
        run: |
          west init -l .
          west update

      - name: Export Zephyr
        run: west zephyr-export

      - name: Build ZMK for shield
        run: |
          echo "Building shield=${{ matrix.shield }} board=${{ matrix.board }}"
          west build -s zmk/app -d build/${{ matrix.shield }} \
            -b ${{ matrix.board }} \
            -- -DZMK_CONFIG=config -DSHIELD=${{ matrix.shield }}
